//Products
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_USER_PRODUCTS = 'GET_USER_PRODUCTS';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const FILTER_PRODUCT = 'FILTER_PRODUCT';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const CLEAR_ALL_PRODUCTS = 'CLEAR_ALL_PRODUCTS';
export const CLEAR_USER_PRODUCTS = 'CLEAR_USER_PRODUCTS';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';
export const ADD_PRODUCT_IMAGE = 'ADD_PRODUCT_IMAGE';
//Alert
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
//Auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const EDIT_USER_PERFIL = 'EDIT_USER_PERFIL';
